### ISSUE TITLE
Aspect ratio validation on Rails 6.1 results in NoMethodError

### ISSUE THREAD

**Issue by connorshea** [igorkasyanchuk/active_storage_validations#93]
I have a `User` with an avatar, like this:

```ruby
class User < ApplicationRecord
  validates :avatar,
    attached: false,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 3.megabytes },
    aspect_ratio: :square
end
```

When I try to upload a file for my avatar on Rails 6 it worked fine. On Rails 6.1, it's busted.

Full backtrace:

```
NoMethodError - undefined method `id' for nil:NilClass:
  active_storage_validations (0.9.0) lib/active_storage_validations/metadata.rb:26:in `read_image'
  active_storage_validations (0.9.0) lib/active_storage_validations/metadata.rb:10:in `metadata'
  active_storage_validations (0.9.0) lib/active_storage_validations/aspect_ratio_validator.rb:31:in `block in validate_each'
  active_storage_validations (0.9.0) lib/active_storage_validations/aspect_ratio_validator.rb:30:in `validate_each'
  activemodel (6.1.0) lib/active_model/validator.rb:153:in `block in validate'
  activemodel (6.1.0) lib/active_model/validator.rb:149:in `validate'
  activesupport (6.1.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
  activesupport (6.1.0) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
  activesupport (6.1.0) lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
  activesupport (6.1.0) lib/active_support/callbacks.rb:603:in `block in default_terminator'
  activesupport (6.1.0) lib/active_support/callbacks.rb:199:in `block in halting'
  activesupport (6.1.0) lib/active_support/callbacks.rb:512:in `block in invoke_before'
  activesupport (6.1.0) lib/active_support/callbacks.rb:512:in `invoke_before'
  activesupport (6.1.0) lib/active_support/callbacks.rb:105:in `run_callbacks'
  activesupport (6.1.0) lib/active_support/callbacks.rb:824:in `_run_validate_callbacks'
  activemodel (6.1.0) lib/active_model/validations.rb:406:in `run_validations!'
  activemodel (6.1.0) lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
  activesupport (6.1.0) lib/active_support/callbacks.rb:106:in `run_callbacks'
  activesupport (6.1.0) lib/active_support/callbacks.rb:824:in `_run_validation_callbacks'
  activemodel (6.1.0) lib/active_model/validations/callbacks.rb:117:in `run_validations!'
  activemodel (6.1.0) lib/active_model/validations.rb:337:in `valid?'
  activerecord (6.1.0) lib/active_record/validations.rb:68:in `valid?'
  activerecord (6.1.0) lib/active_record/validations.rb:84:in `perform_validations'
  activerecord (6.1.0) lib/active_record/validations.rb:47:in `save'
  activerecord (6.1.0) lib/active_record/transactions.rb:296:in `block in save'
  activerecord (6.1.0) lib/active_record/transactions.rb:352:in `block in with_transaction_returning_status'
  activerecord (6.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
  activerecord (6.1.0) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  activerecord (6.1.0) lib/active_record/transactions.rb:296:in `save'
  activerecord (6.1.0) lib/active_record/suppressor.rb:44:in `save'
  activerecord (6.1.0) lib/active_record/persistence.rb:628:in `block in update'
  activerecord (6.1.0) lib/active_record/transactions.rb:352:in `block in with_transaction_returning_status'
  activerecord (6.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
  activerecord (6.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
  activesupport (6.1.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  activesupport (6.1.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  activesupport (6.1.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  activerecord (6.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
  activerecord (6.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
  activerecord (6.1.0) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  activerecord (6.1.0) lib/active_record/persistence.rb:626:in `update'
  app/controllers/users_controller.rb:42:in `block in update'
  actionpack (6.1.0) lib/action_controller/metal/mime_responds.rb:205:in `respond_to'
  app/controllers/users_controller.rb:41:in `update'
  actionpack (6.1.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  actionpack (6.1.0) lib/abstract_controller/base.rb:228:in `process_action'
  actionpack (6.1.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (6.1.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  activesupport (6.1.0) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  sentry-raven (3.1.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  activesupport (6.1.0) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  activesupport (6.1.0) lib/active_support/callbacks.rb:137:in `run_callbacks'
  actionpack (6.1.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
  actionpack (6.1.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
  actionpack (6.1.0) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  activesupport (6.1.0) lib/active_support/notifications.rb:203:in `block in instrument'
  activesupport (6.1.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  activesupport (6.1.0) lib/active_support/notifications.rb:203:in `instrument'
  actionpack (6.1.0) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
  actionpack (6.1.0) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
  activerecord (6.1.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  actionpack (6.1.0) lib/abstract_controller/base.rb:165:in `process'
  actionview (6.1.0) lib/action_view/rendering.rb:39:in `process'
  actionpack (6.1.0) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (6.1.0) lib/action_controller/metal.rb:254:in `dispatch'
  actionpack (6.1.0) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (6.1.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  actionpack (6.1.0) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  actionpack (6.1.0) lib/action_dispatch/journey/router.rb:32:in `serve'
  actionpack (6.1.0) lib/action_dispatch/routing/route_set.rb:842:in `call'
  warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.9) lib/warden/manager.rb:34:in `call'
  rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  rack (2.2.3) lib/rack/etag.rb:27:in `call'
  rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
  rack (2.2.3) lib/rack/head.rb:12:in `call'
  actionpack (6.1.0) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
  actionpack (6.1.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/cookies.rb:689:in `call'
  activerecord (6.1.0) lib/active_record/migration.rb:601:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  activesupport (6.1.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
  actionpack (6.1.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:87:in `protected_app_call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:82:in `better_errors_call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:60:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
  web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
  web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  railties (6.1.0) lib/rails/rack/logger.rb:37:in `call_app'
  railties (6.1.0) lib/rails/rack/logger.rb:26:in `block in call'
  activesupport (6.1.0) lib/active_support/tagged_logging.rb:99:in `block in tagged'
  activesupport (6.1.0) lib/active_support/tagged_logging.rb:37:in `tagged'
  activesupport (6.1.0) lib/active_support/tagged_logging.rb:99:in `tagged'
  railties (6.1.0) lib/rails/rack/logger.rb:26:in `call'
  sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/request_id.rb:26:in `call'
  rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  activesupport (6.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/static.rb:24:in `call'
  rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  actionpack (6.1.0) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
  rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
  sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
  webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
  rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
  railties (6.1.0) lib/rails/engine.rb:539:in `call'
  puma (5.1.1) lib/puma/configuration.rb:246:in `call'
  puma (5.1.1) lib/puma/request.rb:76:in `block in handle_request'
  puma (5.1.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
  puma (5.1.1) lib/puma/request.rb:75:in `handle_request'
  puma (5.1.1) lib/puma/server.rb:431:in `process_client'
  puma (5.1.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

This only seems to effect the aspect ratio validator, as far as I can tell? If I remove the aspect ratio attribute on that method, everything works fine.

This is the line that's broken: https://github.com/igorkasyanchuk/active_storage_validations/blob/3532aad2d511e2e3c52002c85011a8511e2bbc77/lib/active_storage_validations/metadata.rb#L26

My best guess is that this commit removed `find_signed` and broke things, but I'm honestly not sure: https://github.com/rails/rails/commit/31148cd6bef4f3a3059c51c587a8bff78a2e73e3#diff-3c9b81c772d32ff6805463595e04d8d7e9031e875ebf2f9fb964ca1a78b5e56d

**Comment by connorshea** [comment]
Okay, I figured it out. It's definitely from that commit I linked. If I change the method to `find_signed!`, it works. Maybe should have an `if` statement that'll use `find_signed!` if Rails >= 6.1  and `find_signed` otherwise.
